import numpy as np
x = np.arange(8)
print('x  =', x)
print('x + 5 =', x+5)
print('x - 5 =', x-5)
print('-x =', -x)
print('x *5 =', x*5)
print('x / 5 =', x/5)
print('x // 5 =', x//5)
print('x % 5 =', x%5)
print('x ^ 5 =', x**5)
